"""HTML views for the research agent browser surfaces."""

from __future__ import annotations

from html import escape


def graph_html(mermaid_graph: str) -> str:
    """Return a standalone Mermaid graph page."""

    escaped_graph = escape(mermaid_graph)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Deep Research Agent Graph</title>
  <script type="module">
    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
    mermaid.initialize({{ startOnLoad: true, theme: "base" }});
  </script>
  <style>
    body {{
      margin: 0;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: #1d2433;
      background: #f7f8fb;
    }}
    main {{
      max-width: 1040px;
      margin: 0 auto;
      padding: 32px 20px 48px;
    }}
    h1 {{ margin: 0 0 8px; font-size: 28px; letter-spacing: 0; }}
    p {{ margin: 0 0 28px; color: #5d667a; line-height: 1.5; }}
    .graph-shell {{
      overflow: auto;
      border: 1px solid #d8dde8;
      border-radius: 8px;
      background: white;
      padding: 24px;
    }}
    .mermaid {{ min-width: 760px; }}
  </style>
</head>
<body>
  <main>
    <h1>Research Agent Graph</h1>
    <p>The graph loops between local planning and web search, then compresses findings.</p>
    <div class="graph-shell">
      <pre class="mermaid">{escaped_graph}</pre>
    </div>
  </main>
</body>
</html>
"""


def app_html() -> str:
    """Return the browser UI for running the research agent."""

    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Deep Research Agent</title>
  <style>
    :root {
      --ink: #1d2433;
      --muted: #626b7f;
      --line: #d9deea;
      --paper: #f6f7fb;
      --surface: #ffffff;
      --accent: #3267d6;
      --accent-strong: #214da6;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      min-height: 100vh;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--ink);
      background: var(--paper);
    }
    header, .composer {
      background: var(--surface);
      border-bottom: 1px solid var(--line);
      padding: 18px 24px;
    }
    header h1 { margin: 0; font-size: 22px; letter-spacing: 0; }
    header p { margin: 4px 0 0; color: var(--muted); line-height: 1.4; }
    main {
      width: min(980px, 100%);
      margin: 0 auto;
      padding: 24px;
    }
    textarea {
      width: 100%;
      min-height: 140px;
      resize: vertical;
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px;
      font: inherit;
      line-height: 1.45;
    }
    .controls {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-top: 12px;
      flex-wrap: wrap;
    }
    label { color: var(--muted); font-size: 14px; }
    input {
      width: 72px;
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 8px;
      font: inherit;
    }
    button {
      border: 0;
      border-radius: 8px;
      min-height: 40px;
      padding: 10px 16px;
      color: white;
      background: var(--accent);
      font: inherit;
      font-weight: 700;
      cursor: pointer;
    }
    button:hover { background: var(--accent-strong); }
    button:disabled { cursor: wait; opacity: 0.65; }
    .status { color: var(--muted); min-height: 20px; margin-top: 10px; }
    .result {
      margin-top: 20px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: white;
      padding: 18px;
    }
    .result h2 { margin: 0 0 12px; font-size: 18px; }
    pre {
      white-space: pre-wrap;
      overflow-wrap: anywhere;
      line-height: 1.5;
      font-family: inherit;
      margin: 0;
    }
  </style>
</head>
<body>
  <header>
    <h1>Deep Research Agent</h1>
    <p>Paste a research brief. The agent searches the web locally and compresses findings.</p>
  </header>
  <main>
    <section class="composer">
      <form id="research-form">
        <textarea
          id="brief"
          placeholder="Paste the research brief generated by the scope module..."
          autofocus
        ></textarea>
        <div class="controls">
          <label>Iterations <input id="iterations" type="number" min="1" max="5" value="2"></label>
          <label>Results/query <input id="results" type="number" min="1" max="5" value="2"></label>
          <button id="run" type="submit">Run research</button>
        </div>
        <div class="status" id="status"></div>
      </form>
    </section>
    <section class="result" hidden>
      <h2>Compressed Research</h2>
      <pre id="compressed"></pre>
    </section>
    <section class="result" hidden>
      <h2>Raw Notes</h2>
      <pre id="notes"></pre>
    </section>
  </main>
  <script>
    const form = document.querySelector("#research-form");
    const brief = document.querySelector("#brief");
    const iterations = document.querySelector("#iterations");
    const results = document.querySelector("#results");
    const run = document.querySelector("#run");
    const status = document.querySelector("#status");
    const compressedSection = document.querySelectorAll(".result")[0];
    const notesSection = document.querySelectorAll(".result")[1];
    const compressed = document.querySelector("#compressed");
    const notes = document.querySelector("#notes");

    form.addEventListener("submit", async (event) => {
      event.preventDefault();
      const value = brief.value.trim();
      if (!value) return;
      run.disabled = true;
      status.textContent = "Searching and compressing locally...";
      compressedSection.hidden = true;
      notesSection.hidden = true;
      try {
        const response = await fetch("/api/research", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            research_brief: value,
            max_search_iterations: Number(iterations.value),
            max_results_per_query: Number(results.value)
          })
        });
        const payload = await response.json();
        if (!response.ok) throw new Error(payload.error || "Research failed");
        compressed.textContent = payload.compressed_research || "";
        notes.textContent = (payload.raw_notes || []).join("\\n\\n");
        compressedSection.hidden = false;
        notesSection.hidden = false;
        status.textContent = "Research complete.";
      } catch (error) {
        status.textContent = error.message;
      } finally {
        run.disabled = false;
      }
    });
  </script>
</body>
</html>
"""
